In [1]:
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold

In [6]:
from sklearn.datasets import load_iris
df=load_iris()
df.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [8]:
df.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [12]:
print(df.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [14]:
df.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [15]:
df.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [16]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [17]:
X_train,X_test,y_train,y_test=train_test_split(df.data,df.target,test_size=0.3)

In [18]:
classifier1=SVC()
classifier2=LogisticRegression()
classifier3=RandomForestClassifier()

In [19]:
classifier1.fit(X_train,y_train)
classifier2.fit(X_train,y_train)
classifier3.fit(X_train,y_train)

RandomForestClassifier()

In [21]:
classifier1.score(X_test,y_test)

0.9555555555555556

In [24]:
print(classifier2.score(X_test,y_test))
print(classifier3.score(X_test,y_test))

0.9555555555555556
0.9555555555555556


In [46]:
kf=KFold(n_splits=6)

In [47]:
for i,j in kf.split([1,2,3,4,5,6,7,8,9,10,11,12]):
    print(i,j)

[ 2  3  4  5  6  7  8  9 10 11] [0 1]
[ 0  1  4  5  6  7  8  9 10 11] [2 3]
[ 0  1  2  3  6  7  8  9 10 11] [4 5]
[ 0  1  2  3  4  5  8  9 10 11] [6 7]
[ 0  1  2  3  4  5  6  7 10 11] [8 9]
[0 1 2 3 4 5 6 7 8 9] [10 11]


In [48]:
def model_ready(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return(model.score(X_test,y_test))


In [49]:
from sklearn.model_selection import StratifiedKFold
skf=StratifiedKFold(n_splits=3)

In [59]:
for train_index_range,test_index_range in skf.split(df.data,df.target):
    X_tr,X_te,y_tr,y_te=df.data[train_index_range],df.data[test_index_range],df.target[train_index_range],df.target[test_index_range]
    print("Logistic Regression: ",model_ready(LogisticRegression(),X_tr,X_te,y_tr,y_te))
    print("Support Vector: ",model_ready(SVC(),X_tr,X_te,y_tr,y_te))
    print("Random Forest: ",model_ready(RandomForestClassifier(),X_tr,X_te,y_tr,y_te))
    print("\n")

D:\Anaconda\system_requires\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Logistic Regression:  0.98
Support Vector:  0.96
Random Forest:  0.98


Logistic Regression:  0.96
Support Vector:  0.98
Random Forest:  0.94


Logistic Regression:  0.98
Support Vector:  0.94
Random Forest:  0.98




In [ ]:
# from sklearn.model_selection import cross_val_predict
# cross=cross_val_predict(LogisticRegression(),df.data,df.target,cv=3)

D:\Anaconda\system_requires\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [53]:
cross

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [54]:
from sklearn.model_selection import cross_val_score
cr_score=cross_val_score(LogisticRegression(),df.data,df.target,cv=3)

D:\Anaconda\system_requires\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [55]:
cr_score

array([0.98, 0.96, 0.98])

In [60]:
logis_reg=[]
svc=[]
forest=[]

for i in range(3,14):
    logis_reg.append(cross_val_score(LogisticRegression(),df.data,df.target,cv=i))
    svc.append(cross_val_score(LogisticRegression(),df.data,df.target,cv=i))
    forest.append(cross_val_score(LogisticRegression(),df.data,df.target,cv=i))

D:\Anaconda\system_requires\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Anaconda\system_requires\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n

In [65]:
import numpy as np
lo_av=[]
svc_av=[]
forest_av=[]
for i in logis_reg:
    lo_av.append(np.average(i))
for i in svc:
    svc_av.append(np.average(i))
for i in forest:
    forest_av.append(np.average(i))

In [66]:
best=[np.average(lo_av),np.average(svc_av),np.average(forest_av)]

In [67]:
best

[0.9692799917818011, 0.9692799917818011, 0.9692799917818011]